#!/bin/bash
#
# bootstrap installs things.

function bootstrapTerminal() {
	sudo -v #ask password beforehand
	source ~/.dotfiles/installscript
}


echo 'Bootstrap terminal and install tools'
echo '------------------'
echo 'This will reset your terminal. Meaning:'
echo '   oh-my-zsh will be installed (agnoster theme, zsh-syntax-highlighting, zsh-autosuggestions)'
echo '   ~/.zshrc will be overridden and symlinked'
echo '   ~/.vimrc will be overridden and symlinked'
echo '   ~/.b5/Taskfile will be overridden and symlinked'
echo '   a new global-gitignore will be set in the git configuration'
echo '   brew will be (re)installed and used for services (current cellar will be deleted)'
echo '   php, python, services etc will be installed (& started) via brew'
echo '   tools & packages (macOs apps, cli tools, composer, npm) will be installed and configured'
echo 'Are you sure you want to to this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]]; then
   bootstrapTerminal
fi
